version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"

  mysql:
    image: mysql
    environment:
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_DATABASE: mydatabase
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_ALLOW_EMPTY_PASSWORD: 
      MYSQL_RANDOM_ROOT_PASSWORD: 
    ports:
      - "3306:3306"

 # mongodb:
  #  image: mongo
 #   environment:
  #    MONGO_INITDB_ROOT_USERNAME: myuser
  #    MONGO_INITDB_ROOT_PASSWORD: mypassword
   # ports:
   #   - "27017:27017"


#docker-compose up -d